[build]
  command = ""
  functions = "netlify/functions"
  publish = "."

[functions]
  directory = "netlify/functions"
  external_node_modules = ["flask"]

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[dev]
  framework = "#custom"
  command = "python app.py"
  targetPort = 5000
  port = 8888
  publish = "."
  autoLaunch = true
