[build]
  command = "pip install -r requirements.txt"
  functions = "netlify/functions"
  publish = "."

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[dev]
  framework = "#custom"
  command = "python app.py"
  targetPort = 5000
  port = 8888
  publish = "."
  autoLaunch = true
